********PART 1*********

In [2]:
!pip install pandas openpyxl pillow matplotlib numpy

Requirement already satisfied: pandas in c:\users\hp\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: pillow in c:\users\hp\anaconda3\lib\site-packages (12.0.0)
Requirement already satisfied: matplotlib in c:\users\hp\anaconda3\lib\site-packages (3.10.6)
Requirement already satisfied: numpy in c:\users\hp\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\anaconda3\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\hp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import os
import pandas as pd
import numpy as np
from PIL import Image, ImageDraw, ImageFont
from datetime import datetime
import matplotlib.pyplot as plt

In [4]:
folders = [
    "database",
    "assets",
    "output",
    "logs",
    "fonts"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

print("Project folders created successfully.")

Project folders created successfully.

Medical_Certificate_Generator/
│
├── database/
│      employee_data.xlsx
│
├── assets/
├── output/
├── logs/
├── fonts/
│
└── MedicalCertificate.ipynb

In [10]:
import pandas as pd

excel_path = "C:/Users/HP/Downloads/Salary_March 2026 revised (1) By Dam Sir 23.5.26-Final (1).xlsx"

df = pd.read_excel(excel_path)

print("Employee Database Loaded Successfully")

Employee Database Loaded Successfully

In [11]:
df.head()

,Posting District,Place of Posting,Office Code,Designation,Employee Name,eHrms Code,Type,SeniorityNo,Gender,DOB,...,Status,StatusDate,Qualification,Specialization,Service Book Status,Program-SubProgram,EmpStatus,Account Number,UAN,FMR CODE
0,JHANSI,AARI SC,FC12233,COMMUNITY HEALTH OFFICER,VISHNU KUMAR PARMAR,1069301,CONTRACTUAL,NaN,Male,18/07/1990,...,Active,NaT,NaN,NaN,Not Prepared,COMMUNITY PROCESS,On Job,3.022020e+14,NaN,187.1
1,JHANSI,AD JHANSI,FCA0168,COLD CHAIN HALDLER,VIPIN KUMAR,121669,CONTRACTUAL,NaN,Male,01/07/1991,...,Active,NaT,B.C.A,NaN,Verified,Routine Immunization,NaN,3.493228e+10,101054936121 ...,185.C.S0795
2,JHANSI,AD JHANSI,FCA0168,CONSULTANT,FIROZ ALAM,3021866,CONTRACTUAL,NaN,Male,01/07/1974,...,Active,NaT,NaN,NaN,Not Prepared,NUHM,NaN,3.191643e+10,NaN,185.C.S001
3,JHANSI,AD JHANSI,FCA0168,CONSULTANT,FIROZ ALAM,228378,CONTRACTUAL,NaN,Male,01/07/1974,...,Resigned,2018-08-03,PG Diploma,Computer Application,Verified,NUHM,NaN,NaN,NaN,NaN
4,JHANSI,AD JHANSI,FCA0168,DATA ASSISTANT,SHOEB AHMAD,121587,CONTRACTUAL,NaN,Male,27/11/1988,...,Active,NaT,B.Com.,Banking,Not Prepared,Family Planning-PCPNDT,NaN,5.014789e+10,NaN,185.C.P001

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1357 entries, 0 to 1356
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Posting District         1357 non-null   object
 1   Place of Posting         1357 non-null   object
 2   Office Code              1292 non-null   object
 3   Designation              1357 non-null   object
 4   Employee Name            1357 non-null   object
 5   eHrms Code               1357 non-null   int64
 6   Type                     1357 non-null   object
 7   SeniorityNo              0 non-null      float64
 8   Gender                   1355 non-null   object
 9   DOB                      1357 non-null   object
 10  Father Name              1357 non-null   object
 11  Home District            1347 non-null   object
 12  Cadre                    1352 non-null   object
 13  Level in Cadre           0 non-null      float64
 14  esalarycd                1265 non-null   object
 15  Appointment Date         1041 non-null   object
 16  Date of Joining          1357 non-null   object
 17  Service Tenure(in year)  1357 non-null   int64
 18  Date of Retirement       1357 non-null   object
 19  Status                   1357 non-null   object
 20  StatusDate               295 non-null    datetime64[ns]
 21  Qualification            694 non-null    object
 22  Specialization           563 non-null    object
 23  Service Book Status      1357 non-null   object
 24  Program-SubProgram       1344 non-null   object
 25  EmpStatus                630 non-null    object
 26  Account Number           1034 non-null   float64
 27  UAN                      323 non-null    object
 28  FMR CODE                 1016 non-null   object
dtypes: datetime64[ns](1), float64(3), int64(2), object(23)
memory usage: 307.6+ KB

In [13]:
missing = df.isnull().sum()

print(missing)

Posting District              0
Place of Posting              0
Office Code                  65
Designation                   0
Employee Name                 0
eHrms Code                    0
Type                          0
SeniorityNo                1357
Gender                        2
DOB                           0
Father Name                   0
Home District                10
Cadre                         5
Level in Cadre             1357
esalarycd                    92
Appointment Date            316
Date of Joining               0
Service Tenure(in year)       0
Date of Retirement            0
Status                        0
StatusDate                 1062
Qualification               663
Specialization              794
Service Book Status           0
Program-SubProgram           13
EmpStatus                   727
Account Number              323
UAN                        1034
FMR CODE                    341
dtype: int64

In [14]:
print(df.columns.tolist())

['Posting District', 'Place of Posting', 'Office Code', 'Designation', 'Employee Name', 'eHrms Code', 'Type', 'SeniorityNo', 'Gender', 'DOB', 'Father Name', 'Home District', 'Cadre', 'Level in Cadre', 'esalarycd', 'Appointment Date', 'Date of Joining', 'Service Tenure(in year)', 'Date of Retirement', 'Status', 'StatusDate', 'Qualification', 'Specialization', 'Service Book Status', 'Program-SubProgram', 'EmpStatus', 'Account Number', 'UAN', 'FMR CODE']

In [15]:
print("Total Employees :", len(df))

print("\nEmployee Status\n")
print(df["Status"].value_counts())

print("\nQualification\n")
print(df["Qualification"].value_counts())

print("\nDesignation\n")
print(df["Designation"].value_counts())

Total Employees : 1357

Employee Status

Status
Active               1062
Resigned              275
Service Terminate       9
Retiree                 7
Death                   4
Name: count, dtype: int64

Qualification

Qualification
Intermediate                         328
B.A.                                  82
B.Sc.                                 58
High School                           45
B.A.M.S                               30
M.A.                                  23
B.H.M.S                               18
Other PG                              16
M.B.B.S.                              12
B.Com.                                10
M.Com.                                10
B.D.S                                  8
B.PHARMA                               5
M.Sc.                                  5
PG Diploma                             5
Diploma                                4
DCH                                    4
MS                                     3
B.C.A                                  3
Bachelor in Physiotherapy (B.P.T)      3
MD                                     2
DGO                                    2
Master of Public Health (M.P.H.)       2
Ph.D                                   2
8                                      2
Bachelor in Labour Welfare             1
DPH                                    1
L.L.B.                                 1
Master in Physiotherapy (M.P.T)        1
B.E/B.Tech/B.Sc. Engg/AMIE             1
DOMS                                   1
M.Phil                                 1
DORTH                                  1
M.Ch.                                  1
DCP                                    1
B.U.M.S.                               1
Rattan                                 1
Name: count, dtype: int64

Designation

Designation
STAFF NURSE                    324
COMMUNITY HEALTH OFFICER       283
ANM                            237
MO                              98
LAB TECHNICIAN                  78
                              ...
DPM                              1
MIS ASSISTANT                    1
OPERATION THEATRE ASSISTANT      1
CLINICAL PSHYCHOLOGIST           1
WARD SISTER                      1
Name: count, Length: 106, dtype: int64

In [16]:
date_columns = [
    "Appointment Date",
    "Date of Joining"
]

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce")

print("Date Conversion Completed")

Date Conversion Completed

C:\Users\HP\AppData\Local\Temp\ipykernel_2228\4093370367.py:7: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df[col] = pd.to_datetime(df[col], errors="coerce")

In [17]:
today = datetime.today()

df["Calculated Experience"] = (
    (today - df["Date of Joining"]).dt.days / 365.25
).round(1)

df[["Employee Name", "Calculated Experience"]].head()

         Employee Name  Calculated Experience
0  VISHNU KUMAR PARMAR                    7.4
1       VIPIN  KUMAR                     15.4
2           FIROZ ALAM                    7.8
3           FIROZ ALAM                    7.8
4         SHOEB  AHMAD                   12.4

In [18]:
df.to_excel(
    "database/employee_database_cleaned.xlsx",
    index=False
)

print("Cleaned Database Saved Successfully")

Cleaned Database Saved Successfully

In [19]:
sample = df.iloc[0]

print("Employee Name :", sample["Employee Name"])
print("Designation   :", sample["Designation"])
print("Qualification :", sample["Qualification"])
print("Experience    :", sample["Calculated Experience"])

Employee Name : VISHNU KUMAR PARMAR
Designation   : COMMUNITY HEALTH OFFICER
Qualification : nan
Experience    : 7.4

****END_OF_PART_1****